<?php
require_once 'config.php';
requireLogin();
$pageTitle = "Saving Tips & AI Insights";
$activePage = "tips";
include "includes/header.php";
?>
<div class="app-shell">
    <?php include "includes/sidebar.php"; ?>

    <main class="main-content">
        <?php include "includes/topbar.php"; ?>

        <section class="page-content">
            <nav class="breadcrumbs" aria-label="Breadcrumb">
                <a href="index.php">Home</a>
                <span class="bc-sep">/</span>
                <span class="bc-current" aria-current="page">Saving Tips & Insights</span>
            </nav>

            <div class="page-header">
                <div>
                    <p class="eyebrow">Smart Habits, Bigger Balance</p>
                    <h1>Personalized Tips & AI Insights</h1>
                    <p class="muted">Algorithmic advice tailored to your student spending history and budget goals (SRS 1.6 Page 8).</p>
                </div>
                <div class="header-action-group">
                    <button class="outline-btn active" id="tabTipsBtn" onclick="switchTipsTab('tips')">💡 Saving Tips</button>
                    <button class="outline-btn" id="tabAiBtn" onclick="switchTipsTab('ai')">🤖 AI Monthly Insights</button>
                    <button class="outline-btn" id="tabBookmarksBtn" onclick="switchTipsTab('bookmarks')">📌 My Bookmarks & Notes</button>
                </div>
            </div>

            <!-- TAB 1: Personalized Saving Tips Engine (SRS 1.6 Page 8) -->
            <div id="tipsTabSection" class="tips-tab-content">
                <div class="section-subheading">
                    <div>
                        <h3>Personalized Saving Recommendations</h3>
                        <p class="muted">Generated by comparing current spending against your historical averages and budget limits.</p>
                    </div>
                </div>
                <div class="tips-grid" id="personalizedTipsGrid">
                    <article class="tip-panel ranked-tip">
                        <div class="tip-rank-badge high-impact">High Impact — Potential save: Rs. 3,500/mo</div>
                        <span class="tip-number">01</span>
                        <h3>Cap Food Delivery & Campus Cafe</h3>
                        <p>Your food delivery spending is 40% above your baseline. Setting a Rs. 1,000/week dining cap can save substantial allowance.</p>
                        <div class="tip-card-footer">
                            <button class="action-pin-btn" onclick="saveTipBookmark('Cap Food Delivery', 'Setting a Rs. 1,000/week dining cap can save substantial allowance.')">📌 Pin & Bookmark</button>
                            <button class="action-dismiss-btn" onclick="dismissTipElement(this)">Dismiss</button>
                        </div>
                    </article>

                    <article class="tip-panel ranked-tip">
                        <div class="tip-rank-badge med-impact">Medium Impact — Potential save: Rs. 1,200/mo</div>
                        <span class="tip-number">02</span>
                        <h3>Shared Transport / Metro Pass</h3>
                        <p>Transport costs peaked during mid-terms. Switching to an academic monthly pass cuts transit costs by nearly 25%.</p>
                        <div class="tip-card-footer">
                            <button class="action-pin-btn" onclick="saveTipBookmark('Shared Transport Pass', 'Switching to an academic monthly pass cuts transit costs by 25%.')">📌 Pin & Bookmark</button>
                            <button class="action-dismiss-btn" onclick="dismissTipElement(this)">Dismiss</button>
                        </div>
                    </article>

                    <article class="tip-panel ranked-tip">
                        <div class="tip-rank-badge low-impact">Quick Win — Potential save: Rs. 800/mo</div>
                        <span class="tip-number">03</span>
                        <h3>Audit Streaming & App Subscriptions</h3>
                        <p>You have 3 recurring digital subscriptions active. Pausing unused services during exam months protects your emergency buffer.</p>
                        <div class="tip-card-footer">
                            <button class="action-pin-btn" onclick="saveTipBookmark('Audit Subscriptions', 'Pausing unused services during exam months protects your buffer.')">📌 Pin & Bookmark</button>
                            <button class="action-dismiss-btn" onclick="dismissTipElement(this)">Dismiss</button>
                        </div>
                    </article>
                </div>
            </div>

            <!-- TAB 2: AI-Generated Monthly Spending Insights (Module 3) -->
            <div id="aiTabSection" class="tips-tab-content" style="display:none;">
                <?php
                $monthOptions = [];
                for ($i = 0; $i < 12; $i++) {
                    $mVal = date('Y-m', strtotime("-{$i} months"));
                    $mText = date('F Y', strtotime("-{$i} months")) . ($i === 0 ? ' (Current)' : '');
                    $monthOptions[$mVal] = $mText;
                }
                ?>
                <!-- AI Controls Bar -->
                <div class="ai-control-bar">
                    <div class="ai-controls-left">
                        <label for="aiInsightMonth"><strong>Review Month:</strong></label>
                        <select id="aiInsightMonth" class="month-picker-input" onchange="loadAiInsight(this.value, false)">
                            <?php foreach ($monthOptions as $mVal => $mText): ?>
                                <option value="<?php echo htmlspecialchars($mVal); ?>"><?php echo htmlspecialchars($mText); ?></option>
                            <?php endforeach; ?>
                        </select>

                        <div class="ai-slider-wrap">
                            <label for="aiGrowthThreshold">Growth Alert Threshold:</label>
                            <input type="range" id="aiGrowthThreshold" min="10" max="100" step="5" value="25" oninput="document.getElementById('thresholdDisplay').textContent = this.value + '%'">
                            <span class="ai-threshold-val" id="thresholdDisplay">25%</span>
                        </div>
                    </div>
                    <div class="ai-controls-right">
                        <button class="primary-btn" id="generateInsightBtn" onclick="handleGenerateInsight(true)">✨ Generate AI Insight</button>
                        <button class="outline-btn" onclick="handleGenerateInsight(false)" title="Reload review or check for updates">🔄 Refresh</button>
                    </div>
                </div>

                <!-- Opt-Out Notice (Shown when student has AI disabled in settings) -->
                <div id="aiOptedOutAlert" style="display:none; padding:16px 20px; background:#fef2f2; border:1px solid #fecaca; border-radius:12px; margin-bottom:20px; color:#991b1b;">
                    <strong>🔒 AI Category Suggestions & Insights are Disabled</strong>
                    <p style="margin:6px 0 0 0; font-size:13px;">You currently have AI features toggled off. To generate personalized monthly insights and category growth alerts, enable AI features in your <a href="profile.php" style="color:#b91c1c; text-decoration:underline; font-weight:700;">Account Profile Settings</a>.</p>
                </div>

                <!-- Loading State Indicator -->
                <div id="aiLoadingIndicator" style="display:none; text-align:center; padding:45px 20px;">
                    <div class="spinner" style="display:inline-block; width:38px; height:38px; border:3px solid rgba(28,82,83,0.15); border-top-color:var(--teal, #1c5253); border-radius:50%; animation:spin 0.8s linear infinite;"></div>
                    <p style="margin-top:14px; color:var(--muted); font-size:14px; font-weight:500;">Synthesizing monthly transactions & generating plain-language narrative...</p>
                </div>

                <!-- Main Insights Display Container -->
                <div id="aiInsightContainer" style="display:none;">
                    <!-- 1. Monthly Financial KPIs -->
                    <div class="ai-metric-grid">
                        <div class="ai-metric-card">
                            <span class="label">Monthly Income</span>
                            <span class="value" id="kpiIncome" style="color:#1e7e34;">Rs. 0.00</span>
                        </div>
                        <div class="ai-metric-card">
                            <span class="label">Monthly Expenses</span>
                            <span class="value" id="kpiExpense" style="color:#dc2626;">Rs. 0.00</span>
                        </div>
                        <div class="ai-metric-card">
                            <span class="label">Net Savings</span>
                            <span class="value" id="kpiNetSavings">Rs. 0.00</span>
                        </div>
                        <div class="ai-metric-card">
                            <span class="label">Savings Rate</span>
                            <span class="value" id="kpiSavingsRate">0%</span>
                        </div>
                    </div>

                    <!-- 2. Growth Alert Banner -->
                    <div class="ai-alert-banner" id="aiAlertBanner">
                        <span class="ai-badge-warning" id="aiAlertBadge">Growth Alert</span>
                        <strong id="aiGrowthHighlight">Analyzing spending patterns...</strong>
                    </div>

                    <!-- 3. Plain-Language Narrative Card (3-5 Sentences) -->
                    <div class="ai-narrative-card" id="aiNarrativeCard">
                        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:12px; flex-wrap:wrap; gap:8px;">
                            <div style="display:flex; align-items:center; gap:8px;">
                                <span style="font-size:22px;">🤖</span>
                                <h3 style="margin:0; font-size:18px;">Monthly Spending Narrative</h3>
                            </div>
                            <span class="growth-badge-tag ok" id="sentenceBadge">3–5 Sentence Synthesis</span>
                        </div>
                        <p class="ai-summary-text" id="aiNarrativeSummary">
                            "Analyzing monthly transactions..."
                        </p>
                        <div style="display:flex; justify-content:space-between; align-items:center; font-size:12px; color:var(--muted); flex-wrap:wrap; gap:6px;">
                            <span id="aiGeneratedAt">Generated: Just now</span>
                            <span>Historical baseline benchmark: Previous 3 months</span>
                        </div>
                    </div>

                    <!-- 4. Actionable Student Advice Cards -->
                    <div style="margin-bottom:14px;">
                        <h3 style="margin:0 0 4px 0; font-size:18px;">💡 Actionable Spending Adjustments</h3>
                        <p class="muted" style="margin:0; font-size:13px;">Tailored, realistic adjustments based on categories that grew beyond your threshold.</p>
                    </div>
                    <div class="ai-advice-grid" id="aiAdviceGrid">
                        <!-- Populated via JavaScript -->
                    </div>

                    <!-- 5. Category Growth Rates Breakdown Table -->
                    <div class="panel" style="margin-bottom:24px; padding:20px;">
                        <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:14px; flex-wrap:wrap; gap:8px;">
                            <div>
                                <h3 style="margin:0; font-size:17px;">📊 Category Growth vs. Historical Baseline</h3>
                                <p class="muted" style="margin:4px 0 0 0; font-size:12.5px;">Compares current month expense against average spend in prior months.</p>
                            </div>
                            <span id="flaggedCountBadge" class="growth-badge-tag">0 Categories Flagged</span>
                        </div>
                        <div class="table-responsive">
                            <table class="report-table" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th>Category</th>
                                        <th style="text-align:right;">Current Spend</th>
                                        <th style="text-align:right;">Prior 3-Mo Avg</th>
                                        <th style="text-align:right;">Growth Rate</th>
                                        <th style="text-align:center;">Trend Status</th>
                                    </tr>
                                </thead>
                                <tbody id="trendsTableBody">
                                    <!-- Populated via JavaScript -->
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- 6. LLM System Prompt & Payload Inspector -->
                    <details class="panel" style="margin-bottom:24px; padding:16px;">
                        <summary style="cursor:pointer; font-weight:600; font-size:14px; color:var(--teal, #1c5253);">
                            🤖 Developer / API View: Structured LLM Prompt & Payload
                        </summary>
                        <p class="muted" style="margin:8px 0 12px 0; font-size:12.5px;">
                            This structured system and user prompt format can be dispatched directly to external LLM APIs (Gemini, Claude, GPT-4) or handled by the built-in deterministic reasoning engine.
                        </p>
                        <div style="margin-bottom:10px; display:flex; justify-content:flex-end;">
                            <button class="outline-btn btn-sm" onclick="copyLlmPrompt()">📋 Copy Prompt JSON</button>
                        </div>
                        <pre class="llm-inspector-box" id="llmPromptInspector">// Prompt payload will appear here</pre>
                    </details>
                </div>

                <!-- 7. Historical Insights (Past Reviews) -->
                <div class="panel" style="padding:22px; margin-top:24px;">
                    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:16px; flex-wrap:wrap; gap:8px;">
                        <div>
                            <h3 style="margin:0; font-size:18px;">📜 Monthly Review History</h3>
                            <p class="muted" style="margin:4px 0 0 0; font-size:13px;">Review your previously generated monthly insights and trends.</p>
                        </div>
                        <button class="outline-btn btn-sm" onclick="loadAiHistory()">🔄 Refresh History</button>
                    </div>
                    <div id="aiHistoryList">
                        <p class="muted" style="font-size:13px;">Loading insight history...</p>
                    </div>
                </div>
            </div>

            <!-- TAB 3: Bookmarks, Notes & Sharing (SRS 1.6 Page 8) -->
            <div id="bookmarksTabSection" class="tips-tab-content" style="display:none;">
                <div class="section-subheading">
                    <div>
                        <h3>My Saved Tips & Custom Notes</h3>
                        <p class="muted">Personal references and saved advice for your ongoing student financial goals.</p>
                    </div>
                    <button class="primary-btn" onclick="openAddNoteModal()">＋ Add Note</button>
                </div>
                <div class="bookmarks-list" id="savedBookmarksList">
                    <div class="bookmark-item panel">
                        <div class="bookmark-header">
                            <strong>📌 Pinned: Cap Food Delivery</strong>
                            <span class="bookmark-date">Saved on Sept 18</span>
                        </div>
                        <p class="bookmark-body">Setting a Rs. 1,000/week dining cap can save substantial allowance.</p>
                        <div class="bookmark-note">
                            <em>Student Note:</em> "Plan meal prep on Sundays with hostel roommates."
                        </div>
                        <div class="bookmark-actions">
                            <button class="outline-btn btn-sm" onclick="editBookmarkNote(1)">Edit Note</button>
                            <button class="cancel-btn btn-sm" onclick="removeBookmark(1)">Remove</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Bookmark / Add Note Modal -->
        <div class="transaction-modal" id="noteModal" aria-hidden="true">
            <div class="transaction-modal-box">
                <button class="modal-close" type="button" onclick="closeNoteModal()" aria-label="Close dialog">×</button>
                <p class="eyebrow">Personal Finance Notes</p>
                <h2>Add / Edit Note</h2>
                <form id="bookmarkNoteForm" onsubmit="handleSaveNote(event)">
                    <label for="noteTitle">Title
                        <input type="text" id="noteTitle" required placeholder="e.g. Semester Book Budget">
                    </label>
                    <label for="noteContent">Note Content
                        <textarea id="noteContent" rows="4" required placeholder="Write your personal reminder or savings strategy..."></textarea>
                    </label>
                    <div class="transaction-form-actions">
                        <button class="cancel-btn" type="button" onclick="closeNoteModal()"><span class="cancel-icon">×</span>Cancel</button>
                        <button class="primary-btn full-btn" type="submit">Save Bookmark Note</button>
                    </div>
                </form>
            </div>
        </div>

        <?php include "includes/footer.php"; ?>
    </main>
</div>
<script>
let currentPromptPayload = null;

function switchTipsTab(tabName) {
    document.getElementById('tipsTabSection').style.display = tabName === 'tips' ? 'block' : 'none';
    document.getElementById('aiTabSection').style.display = tabName === 'ai' ? 'block' : 'none';
    document.getElementById('bookmarksTabSection').style.display = tabName === 'bookmarks' ? 'block' : 'none';

    document.getElementById('tabTipsBtn').classList.toggle('active', tabName === 'tips');
    document.getElementById('tabAiBtn').classList.toggle('active', tabName === 'ai');
    document.getElementById('tabBookmarksBtn').classList.toggle('active', tabName === 'bookmarks');

    if (tabName === 'ai') {
        const month = document.getElementById('aiInsightMonth').value;
        loadAiInsight(month, false);
        loadAiHistory();
    }
}

function handleGenerateInsight(force = true) {
    const month = document.getElementById('aiInsightMonth').value;
    loadAiInsight(month, force);
}

async function loadAiInsight(month, force = false) {
    const loading = document.getElementById('aiLoadingIndicator');
    const container = document.getElementById('aiInsightContainer');
    const optAlert = document.getElementById('aiOptedOutAlert');
    const genBtn = document.getElementById('generateInsightBtn');

    loading.style.display = 'block';
    container.style.display = 'none';
    optAlert.style.display = 'none';
    if (genBtn) genBtn.disabled = true;

    const threshold = document.getElementById('aiGrowthThreshold').value || 25;

    try {
        const resp = await fetch(`api/generate_insight.php?month=${encodeURIComponent(month)}&threshold=${encodeURIComponent(threshold)}&force=${force ? '1' : '0'}`);
        const data = await resp.json();

        loading.style.display = 'none';
        if (genBtn) genBtn.disabled = false;

        if (!data.success) {
            if (data.opted_out) {
                optAlert.style.display = 'block';
            } else {
                showDemoMessage(data.error || 'Failed to load insight.');
            }
            return;
        }

        renderInsightData(data);
        container.style.display = 'block';
        loadAiHistory(); // Refresh history list after generating
    } catch (err) {
        loading.style.display = 'none';
        if (genBtn) genBtn.disabled = false;
        console.error(err);
        showDemoMessage('Network error generating insight.');
    }
}

function renderInsightData(data) {
    const insight = data.insight;
    const fin = data.financials;
    const trends = data.trends;
    currentPromptPayload = data.prompt_template;

    // 1. KPIs
    document.getElementById('kpiIncome').textContent = 'Rs. ' + Number(fin.income).toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2});
    document.getElementById('kpiExpense').textContent = 'Rs. ' + Number(fin.expense).toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2});
    
    const netEl = document.getElementById('kpiNetSavings');
    netEl.textContent = 'Rs. ' + Number(fin.net_savings).toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 2});
    netEl.style.color = fin.net_savings >= 0 ? '#166534' : '#dc2626';

    const rateEl = document.getElementById('kpiSavingsRate');
    rateEl.textContent = fin.savings_rate + '%';
    rateEl.style.color = fin.savings_rate >= 20 ? '#166534' : (fin.savings_rate >= 0 ? '#92400e' : '#dc2626');

    // 2. Growth Alert Banner
    const alertBanner = document.getElementById('aiAlertBanner');
    const alertBadge = document.getElementById('aiAlertBadge');
    const alertText = document.getElementById('aiGrowthHighlight');
    const narrativeCard = document.getElementById('aiNarrativeCard');

    const hasFlags = insight.flags && insight.flags.length > 0;
    if (hasFlags) {
        alertBanner.className = 'ai-alert-banner';
        alertBadge.className = 'ai-badge-warning';
        alertBadge.textContent = 'Growth Alert';
        alertText.textContent = insight.growth_flag_text || `${insight.flags[0].name} spending rose ${insight.flags[0].growth_percent}% compared to historical trend.`;
        narrativeCard.classList.add('has-flags');
    } else {
        alertBanner.className = 'ai-alert-banner ok';
        alertBadge.className = 'ai-badge-ok';
        alertBadge.textContent = 'Disciplined Pace';
        alertText.textContent = `All categories remained within normal spending limits (threshold: ${insight.threshold_used}%).`;
        narrativeCard.classList.remove('has-flags');
    }

    // 3. Narrative Box
    document.getElementById('aiNarrativeSummary').textContent = `"${insight.summary_text}"`;
    document.getElementById('aiGeneratedAt').textContent = `Generated: ${insight.generated_at ? new Date(insight.generated_at).toLocaleString() : 'Just now'}`;

    // 4. Actionable Advice Grid
    const adviceGrid = document.getElementById('aiAdviceGrid');
    adviceGrid.innerHTML = '';
    const adviceItems = insight.advice || [];

    if (adviceItems.length === 0) {
        adviceGrid.innerHTML = '<p class="muted" style="font-size:13px;">No specific adjustments needed this month.</p>';
    } else {
        adviceItems.forEach(adv => {
            const card = document.createElement('article');
            card.className = 'ai-advice-card';
            card.innerHTML = `
                <div class="ai-advice-card-header">
                    <span class="ai-advice-icon">${escapeHtml(adv.icon || '💡')}</span>
                    <div>
                        <span style="font-size:11px; text-transform:uppercase; font-weight:700; color:var(--teal, #1c5253); letter-spacing:0.5px;">${escapeHtml(adv.category || 'Category')}</span>
                        <h4>${escapeHtml(adv.headline || '')}</h4>
                    </div>
                </div>
                <p>${escapeHtml(adv.advice_text || '')}</p>
                <div style="margin-top:auto; padding-top:8px;">
                    <button class="outline-btn btn-sm" onclick="saveTipBookmark('${escapeJs(adv.headline)}', '${escapeJs(adv.advice_text)}')">📌 Bookmark Advice</button>
                </div>
            `;
            adviceGrid.appendChild(card);
        });
    }

    // 5. Category Growth Breakdown Table
    const tbody = document.getElementById('trendsTableBody');
    tbody.innerHTML = '';
    const allTrends = (trends && trends.all_trends) ? trends.all_trends : [];
    const flaggedCount = (trends && trends.flagged_count) ? trends.flagged_count : 0;
    
    const countBadge = document.getElementById('flaggedCountBadge');
    countBadge.textContent = `${flaggedCount} Categor${flaggedCount === 1 ? 'y' : 'ies'} Flagged`;
    countBadge.className = flaggedCount > 0 ? 'growth-badge-tag' : 'growth-badge-tag ok';

    if (allTrends.length === 0) {
        tbody.innerHTML = '<tr><td colspan="5" style="text-align:center; color:var(--muted); padding:20px;">No expense transactions logged in this period.</td></tr>';
    } else {
        allTrends.forEach(t => {
            const tr = document.createElement('tr');
            const isFlagged = t.is_flagged;
            const growthFormatted = (t.growth_percent >= 0 ? '+' : '') + t.growth_percent.toFixed(1) + '%';
            
            tr.innerHTML = `
                <td style="font-weight:600;">
                    <span style="margin-right:6px;">${escapeHtml(t.icon || '🏷️')}</span>
                    ${escapeHtml(t.name)}
                </td>
                <td style="text-align:right; font-weight:600;">Rs. ${Number(t.current_spend).toLocaleString('en-US', {minimumFractionDigits:2, maximumFractionDigits:2})}</td>
                <td style="text-align:right; color:var(--muted);">Rs. ${Number(t.historical_avg).toLocaleString('en-US', {minimumFractionDigits:2, maximumFractionDigits:2})}</td>
                <td style="text-align:right; font-weight:700; color:${t.growth_percent > 0 ? (isFlagged ? '#dc2626' : '#92400e') : '#166534'};">
                    ${growthFormatted}
                </td>
                <td style="text-align:center;">
                    <span class="growth-badge-tag ${isFlagged ? '' : 'ok'}">
                        ${isFlagged ? '⚠️ Exceeded Threshold' : '✓ Normal Pace'}
                    </span>
                </td>
            `;
            tbody.appendChild(tr);
        });
    }

    // 6. LLM Inspector Box
    const inspector = document.getElementById('llmPromptInspector');
    if (inspector && currentPromptPayload) {
        inspector.textContent = JSON.stringify(currentPromptPayload, null, 2);
    }
}

async function loadAiHistory() {
    const list = document.getElementById('aiHistoryList');
    try {
        const resp = await fetch('api/insight_history.php');
        const data = await resp.json();

        if (!data.success || !data.history || data.history.length === 0) {
            list.innerHTML = '<p class="muted" style="font-size:13px; padding:12px 0;">No saved insights yet. Click "Generate AI Insight" to create your first monthly report!</p>';
            return;
        }

        list.innerHTML = '';
        data.history.forEach(item => {
            const card = document.createElement('div');
            card.className = 'ai-history-card';
            const flagCount = (item.flags && item.flags.length) ? item.flags.length : 0;
            const badgeClass = flagCount > 0 ? 'growth-badge-tag' : 'growth-badge-tag ok';
            
            card.innerHTML = `
                <div class="ai-history-info">
                    <h4>🗓️ ${escapeHtml(item.month_name || item.month_ym)}</h4>
                    <p style="margin-bottom:6px;">${escapeHtml(item.growth_flag_text || item.summary_text.substring(0, 80) + '...')}</p>
                    <small style="color:var(--muted);">Generated on ${new Date(item.generated_at).toLocaleDateString()}</small>
                </div>
                <div style="display:flex; align-items:center; gap:12px;">
                    <span class="${badgeClass}">${flagCount} Flag${flagCount === 1 ? '' : 's'}</span>
                    <button class="outline-btn btn-sm" onclick="event.stopPropagation(); selectHistoryMonth('${escapeJs(item.month_ym)}')">View Review</button>
                </div>
            `;
            card.onclick = () => selectHistoryMonth(item.month_ym);
            list.appendChild(card);
        });
    } catch (err) {
        console.error(err);
        list.innerHTML = '<p class="muted" style="font-size:13px;">Failed to load insight history.</p>';
    }
}

function selectHistoryMonth(ym) {
    const sel = document.getElementById('aiInsightMonth');
    sel.value = ym;
    loadAiInsight(ym, false);
    window.scrollTo({ top: 120, behavior: 'smooth' });
}

function copyLlmPrompt() {
    if (!currentPromptPayload) return;
    const text = JSON.stringify(currentPromptPayload, null, 2);
    navigator.clipboard.writeText(text).then(() => {
        showDemoMessage('LLM Prompt payload copied to clipboard!');
    }).catch(() => {
        showDemoMessage('Failed to copy to clipboard.');
    });
}

function escapeHtml(str) {
    if (!str) return '';
    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

function escapeJs(str) {
    if (!str) return '';
    return String(str).replace(/'/g, "\\'").replace(/"/g, '\\"');
}

function saveTipBookmark(title, text) {
    showDemoMessage('Tip pinned and bookmarked to your saved tips!');
}

function bookmarkCurrentAiInsight() {
    showDemoMessage('Monthly AI Insight bookmarked to your references!');
}

function dismissTipElement(btn) {
    const card = btn.closest('.tip-panel');
    if (card) {
        card.style.opacity = '0';
        card.style.transform = 'scale(0.95)';
        setTimeout(() => card.remove(), 250);
    }
}

function openAddNoteModal() {
    const modal = document.getElementById('noteModal');
    if (modal) {
        modal.classList.add('show');
        modal.setAttribute('aria-hidden', 'false');
    }
}

function closeNoteModal() {
    const modal = document.getElementById('noteModal');
    if (modal) {
        modal.classList.remove('show');
        modal.setAttribute('aria-hidden', 'true');
    }
}

function handleSaveNote(e) {
    e.preventDefault();
    showDemoMessage('Note saved to bookmarks.');
    closeNoteModal();
}
</script>

